{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hncj.sdk",
    "module": "core",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.3.aar",
          "url": "core-1.0.3.aar",
          "size": 168768,
          "sha512": "20b53791d78c4f102d088ece4a594591fcfbb70e162f59e5801406e0b9d6ef1b510296c53c3607b341f267b99bf8f52312fbd487dd646b2440eb9065a872935a",
          "sha256": "83681828d11d60d5fe1993376af2bb9e7ecf72e4e5a26d648616a00afc516208",
          "sha1": "d19ef2ffc2a0f958ee9c2a2a2f21b3c715a94b27",
          "md5": "a7d25a27dd85c061a86bff05e4cea860"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.14.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.qmuiteam",
          "module": "qmui",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.qmuiteam",
          "module": "arch",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.github.lygttpod",
          "module": "SuperTextView",
          "version": {
            "requires": "2.4.6"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.3.aar",
          "url": "core-1.0.3.aar",
          "size": 168768,
          "sha512": "20b53791d78c4f102d088ece4a594591fcfbb70e162f59e5801406e0b9d6ef1b510296c53c3607b341f267b99bf8f52312fbd487dd646b2440eb9065a872935a",
          "sha256": "83681828d11d60d5fe1993376af2bb9e7ecf72e4e5a26d648616a00afc516208",
          "sha1": "d19ef2ffc2a0f958ee9c2a2a2f21b3c715a94b27",
          "md5": "a7d25a27dd85c061a86bff05e4cea860"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.0.3-sources.jar",
          "url": "core-1.0.3-sources.jar",
          "size": 34986,
          "sha512": "5dd8327f2c46f13ca42a33a37cae654bb1b0aea5f6a6a3ae9ee4d2003e81d32aa622a0ab2a8d8be55dcb428bdfeca3cc31fc94ab0d6dfcee17e448af28fa0d60",
          "sha256": "8c7cb857b4c2a81d7e20378e6d355402ee991772cb8b52cf7cf05b4f4a42e374",
          "sha1": "abf384bf24e6f8940c3a7af8448e98c2a496487f",
          "md5": "6f8bbe35c3a1f0243305e41d1cfdc4df"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.0.3-javadoc.jar",
          "url": "core-1.0.3-javadoc.jar",
          "size": 477583,
          "sha512": "fceb51874eec2e4c7fcf6fa6b7b8fd63cb33ce04ed541f263b05203a4f72974a4f7cb080c4e5f5fb3a58a89f647a64f95134ae1fedf2fe40b31bb4c6aed3e605",
          "sha256": "970b6293eaa1632007e633c1fec625819e693e357f7da0785b79c668cb6e0f2e",
          "sha1": "539943919a82257dc6cc478e11d1a293c8b6c449",
          "md5": "7ae437ba87995396b5a08de3f1928838"
        }
      ]
    }
  ]
}
