{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hncj.sdk",
    "module": "login",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "login-1.0.3.aar",
          "url": "login-1.0.3.aar",
          "size": 1427523,
          "sha512": "88a0584160eb9d3394946af41aabc9cda7295239469a8fca83a71f1df629d19a6fe5792b6fe85bd66ba4cfe6a7db845f0eb716a4e294b7bed662793de64a0580",
          "sha256": "bcbc485fed38c9c1c8979dbc470b73051b08c1dddac77076f6c92253173ba03b",
          "sha1": "af8ad3aad8afe01ed5b4ff688bd60c6c846629b6",
          "md5": "b942f45972eb80e1f0bc562f2a9a4fa0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.14.2"
          }
        },
        {
          "group": "com.github.lygttpod",
          "module": "SuperTextView",
          "version": {
            "requires": "2.4.6"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "me.gujun.android",
          "module": "span",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.5.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.android.libraries.identity.googleid",
          "module": "googleid",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-login",
          "version": {
            "requires": "latest.release"
          }
        },
        {
          "group": "com.twitter.sdk.android",
          "module": "twitter-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.linecorp.linesdk",
          "module": "linesdk",
          "version": {
            "requires": "5.12.0"
          }
        },
        {
          "group": "com.navercorp.nid",
          "module": "oauth",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "login-1.0.3.aar",
          "url": "login-1.0.3.aar",
          "size": 1427523,
          "sha512": "88a0584160eb9d3394946af41aabc9cda7295239469a8fca83a71f1df629d19a6fe5792b6fe85bd66ba4cfe6a7db845f0eb716a4e294b7bed662793de64a0580",
          "sha256": "bcbc485fed38c9c1c8979dbc470b73051b08c1dddac77076f6c92253173ba03b",
          "sha1": "af8ad3aad8afe01ed5b4ff688bd60c6c846629b6",
          "md5": "b942f45972eb80e1f0bc562f2a9a4fa0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "login-1.0.3-sources.jar",
          "url": "login-1.0.3-sources.jar",
          "size": 52150,
          "sha512": "fdae261e65aec055c23918a507e5e047492453cae307842e50d7b187ae9b11811b3c4f265d0fc29f030eb68595acd76d09dd395724d16e2eed6facae854029a4",
          "sha256": "a91652e02e18db2d52d50e5668a740b2c9d235e7eead7af5ee66558c96a74e4a",
          "sha1": "7cad2e17b4d37e262c2147297b4a7b5f889b9e69",
          "md5": "3d582c5d8d9f9a7e740e77a539b8501e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "login-1.0.3-javadoc.jar",
          "url": "login-1.0.3-javadoc.jar",
          "size": 558249,
          "sha512": "0f3119987cea72efa1ff909f8f13cc1cd8ad503724ff9f3b35386b68913d0f494232113b829ab7737deda2f2a72dfca41c26197cb9b8b12964141357503e64a7",
          "sha256": "7361605d2ea51eb0882b6ec29a10f7d9ac572f7115db606947747b8c7088d277",
          "sha1": "78889995b901722b21b3abf70717a3d2c55d4b2a",
          "md5": "a67743510c69bff81a3a95ae36700eca"
        }
      ]
    }
  ]
}
