{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hncj.sdk",
    "module": "pay",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "pay-1.0.3.aar",
          "url": "pay-1.0.3.aar",
          "size": 97298,
          "sha512": "8210e9552c78d1e931c272f2bf58a16aef2d6870bdbdf1dff400628ee94f21f0d563a8025d0ef47428ef3b13c409d8fd97ede8df6be980134142a9deab614bc0",
          "sha256": "91fd841362cb6315b6e44c98cfc671e12c88e9ebac257e8e58f64fd35efe75eb",
          "sha1": "73815b7d3f341c8627d45f4325f86e6b018c9630",
          "md5": "202e06c577d02daa72dbc7159e192fb7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.14.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "pay-1.0.3.aar",
          "url": "pay-1.0.3.aar",
          "size": 97298,
          "sha512": "8210e9552c78d1e931c272f2bf58a16aef2d6870bdbdf1dff400628ee94f21f0d563a8025d0ef47428ef3b13c409d8fd97ede8df6be980134142a9deab614bc0",
          "sha256": "91fd841362cb6315b6e44c98cfc671e12c88e9ebac257e8e58f64fd35efe75eb",
          "sha1": "73815b7d3f341c8627d45f4325f86e6b018c9630",
          "md5": "202e06c577d02daa72dbc7159e192fb7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pay-1.0.3-sources.jar",
          "url": "pay-1.0.3-sources.jar",
          "size": 18122,
          "sha512": "023b00bb08eadd134ac51028ec199f81cf4310062d17796f98c331284bdb74c39f60986177a54b4c4a8830247bd11d271bc4310d97b4e24854c264c5c5dd7d92",
          "sha256": "8fc3e2386cfe8066ff2ee061adf39a62deff23d24e32269008f2e435d6cbf10c",
          "sha1": "8eb65bb2d895430fa7971d194943921cf2c29b5f",
          "md5": "f8f6c0312a8435984528c6bc70c225c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pay-1.0.3-javadoc.jar",
          "url": "pay-1.0.3-javadoc.jar",
          "size": 279667,
          "sha512": "76ec5728ab7d6aecb0812b44c808a4f48a757376b70a5183cafd4e8bbdd86c260b74935502ab4b67d5d56b9dd7a723f4f96dfe8efa078a674f38b72323cdd30d",
          "sha256": "ea694b38b9e1de4f4531d50b4e072f9366944975878176832e8820355eeafd23",
          "sha1": "30501635289381646344345812807ff6062e4298",
          "md5": "da7fca2ce322b1e7408204c060b5146e"
        }
      ]
    }
  ]
}
