{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hncj.sdk",
    "module": "login",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "login-1.0.0.aar",
          "url": "login-1.0.0.aar",
          "size": 1344450,
          "sha512": "fcb62b31c8ff0bfc6845922463831eee2962103807bd8a6ec5ff89f7998cc53e8bd5fcd3e20c11cc7649bce9e7190c923f1f2ee879bf9b1cfd7a6a74805f0194",
          "sha256": "d522806eb0580e9032b3b73938044df397e7b1cf1fed02bfe5386f8fc902c07c",
          "sha1": "6cef71eb7715de55b21bf34d60d9d97deb6735d9",
          "md5": "85137b92ff2d8893c2e420cde35af77e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.14.2"
          }
        },
        {
          "group": "com.github.lygttpod",
          "module": "SuperTextView",
          "version": {
            "requires": "2.4.6"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "me.gujun.android",
          "module": "span",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.hncj.android.utils",
          "module": "aes",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.5.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.android.libraries.identity.googleid",
          "module": "googleid",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-login",
          "version": {
            "requires": "latest.release"
          }
        },
        {
          "group": "com.twitter.sdk.android",
          "module": "twitter-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.linecorp.linesdk",
          "module": "linesdk",
          "version": {
            "requires": "5.12.0"
          }
        },
        {
          "group": "com.navercorp.nid",
          "module": "oauth",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "login-1.0.0.aar",
          "url": "login-1.0.0.aar",
          "size": 1344450,
          "sha512": "fcb62b31c8ff0bfc6845922463831eee2962103807bd8a6ec5ff89f7998cc53e8bd5fcd3e20c11cc7649bce9e7190c923f1f2ee879bf9b1cfd7a6a74805f0194",
          "sha256": "d522806eb0580e9032b3b73938044df397e7b1cf1fed02bfe5386f8fc902c07c",
          "sha1": "6cef71eb7715de55b21bf34d60d9d97deb6735d9",
          "md5": "85137b92ff2d8893c2e420cde35af77e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "login-1.0.0-sources.jar",
          "url": "login-1.0.0-sources.jar",
          "size": 41925,
          "sha512": "98164190190b23ba2b0e7b2c911df024565958855e070f18e231423debbe702187d4e8de3837568f32bbc6068c4f1fd656f8d73dc929abed33a4c0df66b4d0d6",
          "sha256": "5880abd6c66fcfb99a8d12fb276af57c1a296d462974f759f4a436d487505280",
          "sha1": "53056a564cdc71325db491118784df623e2dbe29",
          "md5": "e65ed1b48cfbeb489ca573461f341e47"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "login-1.0.0-javadoc.jar",
          "url": "login-1.0.0-javadoc.jar",
          "size": 536833,
          "sha512": "5b3a40cf78941a2cd67f985aa80f669b04dc73296ef639cfb0be0b10f3908aa8588163937f6d3874cfef0880e4a02c991ad9289a48e01864060ca67715e63258",
          "sha256": "11e974d7a9df91e95c6c367098ea41fd1143422636ffecf17faf2831ddb5431b",
          "sha1": "456a483f40c58d84226d643df062b367dfc463ec",
          "md5": "6727e5c44f3086828ad29e2cf2613d24"
        }
      ]
    }
  ]
}
