{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hncj.sdk",
    "module": "login",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "login-1.0.2.aar",
          "url": "login-1.0.2.aar",
          "size": 1344537,
          "sha512": "0b4698fbcd9e8fe053f54a0d3eb0c97696ed3e7b541525c9bb5ff40dbe74cd36efa016dee21147e781e940fba19760e7b1cd03ffef2901be012f5dbd042e220e",
          "sha256": "9ba65dd5c740d944d96cba661de4895fb76424c26fc0d454ef4fd21f5820cf87",
          "sha1": "3c7ca8d3e10250661a2541e1c19c3ccd95cee889",
          "md5": "dc051a41ad6fd632e0901a7d84ae3f2c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.14.2"
          }
        },
        {
          "group": "com.github.lygttpod",
          "module": "SuperTextView",
          "version": {
            "requires": "2.4.6"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "me.gujun.android",
          "module": "span",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.5.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.android.libraries.identity.googleid",
          "module": "googleid",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-login",
          "version": {
            "requires": "latest.release"
          }
        },
        {
          "group": "com.twitter.sdk.android",
          "module": "twitter-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.linecorp.linesdk",
          "module": "linesdk",
          "version": {
            "requires": "5.12.0"
          }
        },
        {
          "group": "com.navercorp.nid",
          "module": "oauth",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "login-1.0.2.aar",
          "url": "login-1.0.2.aar",
          "size": 1344537,
          "sha512": "0b4698fbcd9e8fe053f54a0d3eb0c97696ed3e7b541525c9bb5ff40dbe74cd36efa016dee21147e781e940fba19760e7b1cd03ffef2901be012f5dbd042e220e",
          "sha256": "9ba65dd5c740d944d96cba661de4895fb76424c26fc0d454ef4fd21f5820cf87",
          "sha1": "3c7ca8d3e10250661a2541e1c19c3ccd95cee889",
          "md5": "dc051a41ad6fd632e0901a7d84ae3f2c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "login-1.0.2-sources.jar",
          "url": "login-1.0.2-sources.jar",
          "size": 41611,
          "sha512": "b9de70aacabd0a5ee7970c0c323fa23192d73fd79d599615fdaa0215d3826cb416f0ea2f154adb0ac1c5e6b6d19cca8ed5146b3cd2d9d6233fd3c42308a5399c",
          "sha256": "7e1898e30b6f4a0e3a01e8be6ebfb2d436c7f5d0b0912b5ab7805895ea3f09f5",
          "sha1": "421b670ac1c9847768277a75744fe479ac230e1d",
          "md5": "8fcceb3abb1842b5905228f1d52fda83"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "login-1.0.2-javadoc.jar",
          "url": "login-1.0.2-javadoc.jar",
          "size": 539798,
          "sha512": "587259eaad342979cbefd6e671060431a85d5717e52b5551f5e1c6bd1f8d1981bb93744ac95f0ac1c13ef6ae7b0bc600ea3d81be4d49c28852bdc4752617ac6a",
          "sha256": "919250e5bf7b43d378e0f47f99359b1b931b83dc2620fad7fc4f7b6b8c0ba464",
          "sha1": "38fce9396d343d968158b121e5caf4311f6e71b5",
          "md5": "324db94c9d73a87f8ad75bd12c2a57f2"
        }
      ]
    }
  ]
}
