{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hncj.sdk",
    "module": "core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0.aar",
          "url": "core-1.0.0.aar",
          "size": 168578,
          "sha512": "35123f6f38787db23cc6d3935d71e6da418815263391a6ef06c67f1e98bba3be9059a87671c528d44fc43d80641f578ef1f81308c0a204e0315d5ebeb936795b",
          "sha256": "ec73884360c33d1569292cddf1ca8d84d9e5a61379b8dbfc2c486db85385c972",
          "sha1": "a3d293a032e49e239ca3aec90dbadf7384422ba1",
          "md5": "2025d1c627a7732df65d17693f2175f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.14.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.hncj.android.utils",
          "module": "aes",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.qmuiteam",
          "module": "qmui",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.qmuiteam",
          "module": "arch",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.github.lygttpod",
          "module": "SuperTextView",
          "version": {
            "requires": "2.4.6"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0.aar",
          "url": "core-1.0.0.aar",
          "size": 168578,
          "sha512": "35123f6f38787db23cc6d3935d71e6da418815263391a6ef06c67f1e98bba3be9059a87671c528d44fc43d80641f578ef1f81308c0a204e0315d5ebeb936795b",
          "sha256": "ec73884360c33d1569292cddf1ca8d84d9e5a61379b8dbfc2c486db85385c972",
          "sha1": "a3d293a032e49e239ca3aec90dbadf7384422ba1",
          "md5": "2025d1c627a7732df65d17693f2175f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.0.0-sources.jar",
          "url": "core-1.0.0-sources.jar",
          "size": 34913,
          "sha512": "6d5b7ec53aaa7a8c5e3594dcb5da1cbe94c182687b2be8eba3876f241437087d4b8fc3ccf0f555fb3f20b14d2255a02b99e367f83bd11b482317791fab7ff102",
          "sha256": "5ad4024b7cf1454a314075ad9c37965b8b7d3563e5c9110559794ffef2cc9088",
          "sha1": "649502a548607baf613764c55978c133827c5f19",
          "md5": "34a004f5ab94b40098d31eff4ffb0bb7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.0.0-javadoc.jar",
          "url": "core-1.0.0-javadoc.jar",
          "size": 471657,
          "sha512": "09aeccc3458724b5ea40d778611bd17377a74d2a545111234e5cd5baf1ca00410468795a1337f54f435734faa186ae9f99d13baca2fa745ac2ee668d85aa72f0",
          "sha256": "809c38e29e2c51ceb6a433b203482a50760d3e826d04f866178261f44764e8da",
          "sha1": "592807bfc7e2d1e5386c73bb71e3b03c0d7a0a90",
          "md5": "2964548dae648015149daca310d07f82"
        }
      ]
    }
  ]
}
